# Generated by Django 5.2.4 on 2025-07-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_fruit_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit')),
                ('price_per_kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_details', to='fruits.fruit')),
            ],
        ),
    ]
