# Generated by Django 5.2.4 on 2025-07-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0005_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserMy',
        ),
    ]
