# Generated by Django 5.2.4 on 2025-07-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0006_rename_user_usermy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMy',
            new_name='user_custom',
        ),
    ]
