# Generated by Django 5.2.4 on 2025-07-09 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0007_rename_usermy_user_custom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FruitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fruit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='fruits.fruit')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='fruit_details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fruit_details',
            name='price_per_kg',
        ),
        migrations.DeleteModel(
            name='user_custom',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Fruit_details',
        ),
    ]
