# Generated by Django 5.1.7 on 2025-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0008_cartitem_fruitdetail_remove_cart_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
